# Generated by Django 5.0.4 on 2024-05-08 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskQueries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qry_name', models.CharField(max_length=100, unique=True)),
                ('qry', models.TextField(help_text='Enter query here')),
                ('create_by', models.CharField(max_length=20)),
                ('create_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created 0n')),
                ('last_accessed', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Last time this query was accessed', null=True, verbose_name='Last accessed')),
                ('num_visit', models.PositiveIntegerField(default=1, verbose_name='Num of visits to this qry')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
                'db_table': 'tb_queries',
                'ordering': ['qry_name'],
            },
        ),
    ]
