# Generated by Django 5.1.3 on 2024-11-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.FloatField(help_text='X-axis value for both graphs')),
                ('y_value', models.FloatField(help_text='Y-axis value for scatter plot')),
                ('line_value', models.FloatField(help_text='Y-axis value for line graph')),
                ('category', models.CharField(blank=True, help_text='Optional category for data grouping', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['x_value'],
            },
        ),
    ]
