# Generated by Django 5.0.4 on 2024-05-02 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('contact_details', models.TextField(help_text='Contact information of the vendor')),
                ('address', models.TextField(help_text='Physical address of the vendor')),
                ('vendor_code', models.CharField(max_length=10, unique=True)),
                ('on_time_delivery_rate', models.FloatField(help_text='Tracks the percentage of on-time deliveries')),
                ('quality_rating_avg', models.FloatField(help_text='Average rating of quality based on purchase orders')),
                ('average_response_time', models.FloatField(help_text='Average time taken to acknowledge purchase orders')),
                ('fulfillment_rate', models.FloatField(help_text='Percentage of purchase orders fulfilled successfully')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=10, unique=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendor', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('on_time_delivery_rate', models.FloatField()),
                ('quality_rating_avg', models.FloatField()),
                ('average_response_time', models.FloatField()),
                ('fulfillment_rate', models.FloatField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendor')),
            ],
        ),
    ]
