# Generated by Django 5.0.4 on 2024-05-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_purchaseorder_quality_rating_purchaseorder_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='items',
            field=models.JSONField(default=''),
        ),
    ]
