# Generated by Django 5.0.4 on 2024-05-05 08:54

import api.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_historicalperformance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of the performance record'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[(api.models.OrderStatus['PENDING'], api.models.OrderStatus['PENDING']), (api.models.OrderStatus['COMPLETED'], api.models.OrderStatus['COMPLETED']), (api.models.OrderStatus['CANCELLED'], api.models.OrderStatus['CANCELLED'])], default=api.models.OrderStatus['PENDING'], max_length=10),
        ),
    ]
