# Generated by Django 5.0.4 on 2024-06-09 16:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_historicalperformance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(default=api.models.random_code, editable=False, max_length=10, unique=True),
        ),
    ]
