version: '3.2'

#This docker-compose.yml works fine with need for Dockerfile.
#NOTE: You would have to goto http://127.0.0.1:8069/web/database/manager to restore previous DB if any, or http://127.0.0.1:8069/web/login for fresh.
#The other URL would give you Internal Server Error
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        CI_JOB_TOKEN: ${CI_JOB_TOKEN}
        GITLAB_PRIVATE_ACCESS_TOKEN: ${GITLAB_PRIVATE_ACCESS_TOKEN}
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    env_file: .env

  mydb:
    image: postgres:15
    env_file: .env
    ports:
      - "5432:5432"
    
volumes:
  odoo-web-data:
  

