version: '3.2'

#This docker-compose.yml works fine  WITHOUT the need for Docker file.
services:
  web:
    image: odoo:15.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    env_file: .env

  mydb:
    image: postgres:15
    env_file: .env
    ports:
      - "5432:5432"
    
volumes:
  odoo-web-data:
  

